Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"

      node.vm.network "private_network",
        ip: "192.168.56.10#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "k3s-node#{i}"
        vb.memory = 4096
        vb.cpus = 2
      end
    end
  end
end