import { registerPermissions } from '../../permissions/registry';
import { registerWidgetTypes } from './widget-registry';

registerPermissions('events', 'System Events', [
  { name: 'read', description: 'View system event entries' },
], 'Controls access to the Events Viewer widget - roles with read can query and export event records.');

registerPermissions('notifications', 'Notifications', [
  { name: 'view', description: 'View notification profiles and channels' },
  { name: 'manage', description: 'Manage notification profiles and channels' },
], 'Controls access to the Notifications widget - roles with view can inspect settings; roles with manage can configure email/telegram channels and notification profiles.');

registerPermissions('organisations', 'Organisation Manager', [
  { name: 'view', description: 'View organisations and their settings' },
  { name: 'change', description: 'Create, edit, and delete organisations' },
], 'Controls access to the Organisation Manager widget - roles with view can inspect organisations; roles with change can create, edit, and delete organisations.');

registerPermissions('permissions', 'Role Permissions Manager', [
  { name: 'view', description: 'View role permissions' },
  { name: 'manage', description: 'Manage role permissions' },
], 'Controls access to this Permissions Manager widget - roles with view can inspect permissions; roles with manage can edit permissions for all other roles.');

registerPermissions('reports', 'PDF Reports', [
  { name: 'view', description: 'View and preview PDF report templates' },
  { name: 'manage', description: 'Create, edit, and generate PDF reports' },
], 'Controls access to the PDF Report Template Manager - roles with view can inspect and preview templates; roles with manage can design templates and generate PDF reports.');

registerPermissions('scheduler', 'Scheduler', [
  { name: 'view', description: 'View scheduled tasks and run history' },
  { name: 'manage', description: 'Create, edit, and run scheduled tasks' },
], 'Controls access to the Scheduler widget - roles with view can inspect recurring jobs; roles with manage can create, edit, and run them.');

registerPermissions('tagcalcs', 'Tag Calcs', [
  { name: 'view', description: 'View tag calcs' },
  { name: 'manage', description: 'Create, edit, and delete tag calcs' },
], 'Controls access to Tag Calcs - roles with view can inspect computed tag expressions; roles with manage can create, edit, and delete them.');

registerPermissions('users', 'User Accounts', [
  { name: 'view', description: 'View user accounts' },
  { name: 'manage', description: 'Manage user accounts' },
], 'Controls access to the User Manager widget - roles with view can inspect user accounts; roles with manage can create, edit, and reset passwords for user accounts.');

registerWidgetTypes([
  {
    type: 'area-map-widget',
    name: 'Area Map',
    icon: '\u{1F5FA}\uFE0F',
    category: 'General',
    defaultW: 12,
    defaultH: 20,
    minW: 8,
    minH: 12,
    load: () => import('./map-widget'),
  },
  {
    type: 'device-list-widget',
    name: 'Device List',
    icon: '\u{1F4CB}',
    category: 'General',
    defaultW: 16,
    defaultH: 20,
    minW: 10,
    minH: 10,
    load: () => import('./device-list-widget'),
  },
  {
    type: 'text-widget',
    name: 'Text',
    icon: '\u{1F4DD}',
    category: 'General',
    defaultW: 6,
    defaultH: 1,
    minW: 2,
    minH: 1,
    load: () => import('./text-widget'),
  },
  {
    type: 'html-widget',
    name: 'HTML',
    icon: '\u{1F310}',
    category: 'General',
    defaultW: 8,
    defaultH: 4,
    minW: 2,
    minH: 1,
    load: () => import('./html-widget'),
  },
  {
    type: 'previous-period-widget',
    name: 'Previous Period',
    icon: '\u23F1',
    category: 'General',
    defaultW: 6,
    defaultH: 1,
    minW: 3,
    minH: 1,
    load: () => import('./previous-period-widget'),
  },
  {
    type: 'time-range-widget',
    name: 'Time Range',
    icon: '\u{1F4C5}',
    category: 'General',
    defaultW: 6,
    defaultH: 1,
    minW: 4,
    minH: 1,
    load: () => import('./time-range-widget'),
  },
  {
    type: 'big-number-widget',
    name: 'Big Number',
    icon: '\u{1F522}',
    category: 'Metrics',
    defaultW: 6,
    defaultH: 5,
    minW: 1,
    minH: 1,
    load: () => import('./big-number-widget'),
  },
  {
    type: 'gauge-widget',
    name: 'Gauge',
    icon: '\u{1F3AF}',
    category: 'Metrics',
    defaultW: 5,
    defaultH: 6,
    minW: 3,
    minH: 4,
    load: () => import('./gauge-widget'),
  },
  {
    type: 'status-table-widget',
    name: 'Status Table',
    icon: '\u{1F4CB}',
    category: 'Metrics',
    defaultW: 6,
    defaultH: 8,
    minW: 3,
    minH: 3,
    load: () => import('./status-table-widget'),
  },
  {
    type: 'timeseries-chart-widget',
    name: 'Timeseries Chart',
    icon: '\u{1F4C8}',
    category: 'Metrics',
    defaultW: 12,
    defaultH: 8,
    minW: 6,
    minH: 4,
    load: () => import('./timeseries-chart-widget'),
  },
  {
    type: 'binary-status-line-widget',
    name: 'Binary Status Line',
    icon: '\u25AC',
    category: 'Metrics',
    defaultW: 12,
    defaultH: 3,
    minW: 4,
    minH: 2,
    load: () => import('./binary-status-line-widget'),
  },
  {
    type: 'dashboard-nav-widget',
    name: 'Dashboard Nav',
    icon: '\u{1F4CA}',
    category: 'Layout',
    defaultW: 6,
    defaultH: 4,
    minW: 3,
    minH: 3,
    load: () => import('./dashboard-nav-widget'),
  },
  {
    type: 'array-layout-widget',
    name: 'Array Layout',
    icon: '\u{1F532}',
    category: 'Layout',
    defaultW: 12,
    defaultH: 8,
    minW: 4,
    minH: 3,
    load: () => import('./array-layout-widget'),
  },
  {
    type: 'tabs-widget',
    name: 'Tabs',
    icon: '\u{1F4D1}',
    category: 'Layout',
    defaultW: 12,
    defaultH: 8,
    minW: 4,
    minH: 3,
    load: () => import('./tabs-widget'),
  },
  {
    type: 'users-widget',
    name: 'User Manager',
    icon: '\u{1F464}',
    category: 'System',
    defaultW: 12,
    defaultH: 24,
    minW: 8,
    minH: 12,
    load: () => import('./users-widget'),
  },
  {
    type: 'organisations-widget',
    name: 'Organisation Manager',
    icon: '\u{1F3E2}',
    category: 'System',
    defaultW: 12,
    defaultH: 28,
    minW: 10,
    minH: 18,
    load: () => import('./organisations-widget'),
  },
  {
    type: 'permissions-widget',
    name: 'Permissions Manager',
    icon: '\u{1F510}',
    category: 'System',
    defaultW: 12,
    defaultH: 20,
    minW: 8,
    minH: 10,
    load: () => import('./permissions-widget'),
  },
  {
    type: 'tags-manager-widget',
    name: 'Tags Manager',
    icon: '\u{1F3F7}\uFE0F',
    category: 'System',
    defaultW: 12,
    defaultH: 16,
    minW: 8,
    minH: 8,
    load: () => import('./tags-manager-widget'),
  },
  {
    type: 'pdf-template-widget',
    name: 'PDF Reports',
    icon: '\u{1F4C4}',
    category: 'System',
    defaultW: 12,
    defaultH: 24,
    minW: 10,
    minH: 16,
    load: () => import('./pdf-template-widget'),
  },
  {
    type: 'events-viewer-widget',
    name: 'Events Viewer',
    icon: '\u{1F4CB}',
    category: 'System',
    defaultW: 20,
    defaultH: 28,
    minW: 1,
    minH: 1,
    load: () => import('./events-viewer-widget'),
  },
  {
    type: 'notifications-widget',
    name: 'Notifications',
    icon: '\u{1F514}',
    category: 'System',
    defaultW: 12,
    defaultH: 24,
    minW: 8,
    minH: 12,
    load: () => import('./notifications-widget'),
  },
  {
    type: 'tagcalcs-widget',
    name: 'Tag Calcs',
    icon: '\u2A0D',
    category: 'System',
    defaultW: 12,
    defaultH: 24,
    minW: 8,
    minH: 10,
    load: () => import('./tagcalcs-widget'),
  },
  {
    type: 'manual-widget',
    name: 'Help Manual',
    icon: '\u{1F4D6}',
    category: 'System',
    defaultW: 24,
    defaultH: 28,
    minW: 12,
    minH: 8,
    load: () => import('./manual-widget'),
  },
  {
    type: 'scheduler-widget',
    name: 'Scheduler',
    icon: '\u23F1',
    category: 'System',
    defaultW: 24,
    defaultH: 16,
    minW: 12,
    minH: 8,
    load: () => import('./scheduler-widget'),
  },
  {
    type: 'svg-diagram-widget',
    name: 'SVG Diagram',
    icon: 'SVG',
    category: 'Custom',
    defaultW: 16,
    defaultH: 18,
    minW: 8,
    minH: 8,
    load: () => import('./svg-diagram-widget'),
  },
]);
